### ISSUE TITLE
你好，请问这个界面ui设计是什么风格的

### ISSUE THREAD

**Issue by xklong** [Luo-DH/OutCat#10]
想学习您这种开发模式，摆脱autojs开发这种基于无障碍的安卓应用，请问应该学习哪一门编程语言，谢谢

**Comment by Luo-DH** [comment]
你照着这个项目学就可以，原生开发来的，你说的autojs无非也是基于我这种方式实现的；
预言层面就是Kotlin/Java

**Comment by xklong** [comment]
> 

好的，非常感谢
